app/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# from .forms import CaptchaPasswordResetForm


urlpatterns = [
    path('logout_user/', views.logout_view, name="logout_user"),
    path('register_user/', views.register_user, name="register"),
    path('help/', views.help, name="help"),
    path('password/', views.change_password, name='change_password'),
    path('logout_user/', views.logout_view, name="logout_user"),
    path('signin/', views.login_user, name="signin"),
    path("password_reset/", auth_views.PasswordResetView.as_view()),

    # path("password_reset/", auth_views.PasswordResetView.as_view(form_class=CaptchaPasswordResetForm)),

] 

app/criticalpath/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings


from . import views

app_name='criticalpath'
urlpatterns = [
    path('journeys/', views.journey_list, name='journey_list'),
    path('my-criticalpath/', views.UserCriticalPathDetailView.as_view(), name='my-criticalpath'),
    # path('my-saved-journeys', views.UserSavedJourneysListView.as_view(), name='my-saved-journeys'),
    # path('journey/<int:pk>/', views.JourneyDetailView.as_view(), name='journey_detail'),
    # path('journey/create/',
    #     views.JourneyCreateView.as_view(success_url=reverse_lazy('criticalpath:phase_create')), name='journey_create'),
    # path('journey/<int:pk>/update/',
    #     views.JourneyUpdateView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_update'),
    # path('journey/<int:pk>/delete/',
    #     views.JourneyDeleteView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_delete'),
    # path('journey/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    # path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy('journey_list')), name='comment_delete'),
    # path('journey/<int:pk>/favorite',
    #     views.AddFavoriteView.as_view(), name='journey_favorite'),
    # path('journey/<int:pk>/unfavorite',
    #     views.DeleteFavoriteView.as_view(), name='journey_unfavorite'),
    # path('journey/<int:journey_pk>/resource/', views.ResourceAddView.as_view(success_url=reverse_lazy('criticalpath:journey_detail')), name='resource_add'),

    path('resource/create/', views.ResourceCreateView.as_view(success_url=reverse_lazy('home')), name='resource_create'),
    path('resource/<int:resource_pk>/', views.ResourceDetailView.as_view(), name='resource_detail'),
    path('resource/<int:resource_pk>/update/', views.ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/<int:resource_pk>/delete/', views.ResourceDeleteView.as_view(), name='resource_delete'),

    path('ebook/create/', views.EbookCreateView.as_view(success_url=reverse_lazy('home')), name='ebook_create'),
    path('ebook/<int:ebook_pk>/splits/', views.EbookPaymentSplitsView.as_view(), name='ebook_add_splits'),
    path('ebook/<int:ebook_pk>/', views.EbookDetailView.as_view(), name='ebook_detail'),
    path('ebook/<int:ebook_pk>/update/', views.EbookUpdateView.as_view(), name='ebook_update'),
    path('ebook/<int:ebook_pk>/delete/', views.EbookDeleteView.as_view(), name='ebook_delete'),

    path('workshop/create/', views.WorkshopCreateView.as_view(success_url=reverse_lazy('home')), name='workshop_create'),
    path('workshop/<int:workshop_pk>/splits/', views.WorkshopPaymentSplitsView.as_view(), name='workshop_add_splits'),
    path('workshop/<int:workshop_pk>/', views.WorkshopDetailView.as_view(), name='workshop_detail'),
    path('workshop/<int:workshop_pk>/update/', views.WorkshopUpdateView.as_view(), name='workshop_update'),
    path('workshop/<int:workshop_pk>/delete/', views.WorkshopDeleteView.as_view(), name='workshop_delete'),

    path('course/create/', views.CourseCreateView.as_view(success_url=reverse_lazy('criticalpath:creator')), name='course_create'),
    path('course/<int:course_pk>/add/', views.CourseAddResourcesView.as_view(), name='course_add_resources'),
    path('course/<int:course_pk>/splits/', views.CoursePaymentSplitsView.as_view(), name='course_add_splits'),
    path('course/<int:course_pk>/resource/<int:resource_pk>/', views.CourseResourceDetailView.as_view(), name='course_resource_detail'),
    path('course/<int:course_pk>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('course/<int:course_pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course/<int:course_pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),



    path('creator/', views.creation_list, name="my-creations"),
    path('creator/signup/', views.creator_signup, name="creator_signup"),

    # uncomment if you want to enable rewards
    # path('course/<int:course_pk>/resource/<int:resource_pk>/reward/', views.reward_user, name="resource_reward_user"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/emeralize/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy, include
from marketplace.views import homepage
from marketplace import views
from accounts.views import confirm
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from django_email_verification import urls as email_urls  # include the urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="home"),
    path('', include('marketplace.urls')),
    path('', include('criticalpath.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(email_urls)),  # connect them to an arbitrary path
    # path('email/<str:token>/', confirm), # remember to set the "token" parameter in the url!


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "marketplace.views.handle_not_found"

# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL,  
                        document_root=settings.MEDIA_ROOT) 

app/marketplace/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from marketplace import views
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static


app_name='marketplace'
urlpatterns = [
    path('marketplace/', discover, name='discover'),
    path('marketplace/resources/', resource_list, name='resource_list'),
    path('journey/<int:pk>/buy/', journey_buy_view, name="journey_buy"),

    path('resource/<int:pk>/buy/', resource_buy_view, name="resource_buy"),
    path('resource/purchase_detail/<int:pk>/', views.ResourcePurchaseDetailView.as_view(), name="resource_purchase_detail"),
    path('resource/<int:resource>/buy/success/', resource_success, name="resource_success"),

    path('ebook/<int:pk>/buy/', ebook_buy_view, name="ebook_buy"),
    path('ebook/purchase_detail/<int:pk>/', views.EbookPurchaseDetailView.as_view(), name="ebook_purchase_detail"),
    path('ebook/<int:ebook>/buy/success/', ebook_success, name="ebook_success"),

    path('workshop/<int:pk>/buy/', workshop_buy_view, name="workshop_buy"),
    path('workshop/purchase_detail/<int:pk>/', views.WorkshopPurchaseDetailView.as_view(), name="workshop_purchase_detail"),
    path('workshop/<int:workshop>/buy/success/', workshop_success, name="workshop_success"),

    path('course/purchase_detail/<int:pk>/', views.CoursePurchaseDetailView.as_view(), name="course_purchase_detail"),
    path('course/<int:pk>/buy/', course_buy_view, name="course_buy"),
    path('course/<int:course>/buy/success/', course_success, name="course_success"),

    path('journey/<int:journey>/buy/success/', journey_success, name="journey_success"),
    path('webhook/zbd/', csrf_exempt(zbd_webhook), name="charge_callback"),
    path('charge-status/', charge_status_check),
    path('purchase-history/', purchase_history, name="purchase-history"),
    path('transaction-history/', transaction_history, name="transaction-history"),
    path('accounts/profile/', views.UserProfileCreate.as_view(), name="account-profile"),
    path('profile/<username>/', profile, name="user-profile"),
    path('profile/<username>/tip/', tip_amount, name="tip-amount"),
    path('profile/<username>/tip/pay/', tip_pay, name="tip-pay"),
    path('profile/<username>/tip/pay/success/', tip_success, name="tip-success"),
    path('wallet/', wallet_view, name="wallet"),
    path('withdrawal/', withdrawal, name="withdrawal"),
    path('terms/', terms, name="terms"),
    path('privacy/', privacy, name="privacy"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/marketplace/models.py
from django.db import models
from django.db.models.fields import CharField, PositiveIntegerField, TextField
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save



# Create your models here.
class FeaturedCreators(models.Model):
    sequence_number = PositiveIntegerField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

class FeaturedCourses(models.Model):
    sequence_number = PositiveIntegerField()
    course = models.ForeignKey("criticalpath.Course", on_delete=models.CASCADE, null=True, blank=True)

class FeaturedEbooks(models.Model):
    sequence_number = PositiveIntegerField()
    ebook = models.ForeignKey("criticalpath.Ebook", on_delete=models.CASCADE, null=True, blank=True)

class FeaturedWorkshops(models.Model):
    sequence_number = PositiveIntegerField()
    workshop = models.ForeignKey("criticalpath.Workshop", on_delete=models.CASCADE, null=True, blank=True)

class UserProfile(models.Model):
    lightning_address = models.EmailField(null=True, blank=True)
    creator = models.BooleanField(default=False, null=True, blank=False)
    bio = models.TextField(null=True, blank=True)
    profile_pic = models.ImageField(default="img1.jpg" ,upload_to='resource/profile_pics/%Y/%m/%D/', null=True, blank=False)
    tiktok_username = models.CharField(max_length=255, null=True, blank=True)
    youtube_username = models.CharField(max_length=255, null=True, blank=True)
    twitter_username = models.CharField(max_length=255, null=True, blank=True)
    twitch_username = models.CharField(max_length=255, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + " 's Profile"



# this is to create a wallet and profile each time a new user is created
@receiver(post_save, sender=User)
def wallet_profile_create(sender, instance=None, created=False, **kwargs):
    if created:
        Wallet.objects.create(user=instance,)
        UserProfile.objects.create(user=instance,)



class Charge(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    description = models.CharField(max_length=1000)
    amount = models.PositiveIntegerField()
    status = models.CharField(max_length=1000)
    unit = models.CharField(max_length=50)
    internal_id = models.CharField(max_length=1000)
    external_id = models.CharField(max_length=1000)
    callback_url = models.URLField()
    charge_encoded = models.CharField(max_length=1000)
    uri = models.CharField(max_length=1000)
    fee = PositiveIntegerField(blank=True, null=True)
    created_at = models.CharField(max_length=1000)
    expires_at = models.CharField(max_length=1000)
    last_modified_at = models.DateTimeField(auto_now=True)
    user_credited = models.BooleanField(default=False)

    def __str__(self):
        return self.external_id

class Withdrawal(models.Model):
    amount = PositiveIntegerField()
    unit = CharField(max_length=1000)
    status = CharField(max_length=500, blank=True, null=True)
    external_id = CharField(max_length=1000)
    internal_id = CharField(max_length=1000)
    description = TextField()
    callback_url = models.URLField()
    lnurl_withdrawal_encoded = CharField(max_length=1000)
    uri = CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.CharField(max_length=1000)
    user_credited = models.BooleanField(default=False)


    def __str__(self):
        return self.external_id

class Purchase(models.Model):
    charge = models.ForeignKey(Charge, on_delete=models.CASCADE, null=True, blank=True)
    resource = models.ForeignKey("criticalpath.Resource", on_delete=models.CASCADE, null=True, blank=True)
    journey = models.ForeignKey("criticalpath.Journey", on_delete=models.CASCADE, null=True, blank=True)
    course = models.ForeignKey("criticalpath.Course", on_delete=models.CASCADE, null=True, blank=True)
    ebook = models.ForeignKey("criticalpath.Ebook", on_delete=models.CASCADE, null=True, blank=True)
    workshop = models.ForeignKey("criticalpath.Workshop", on_delete=models.CASCADE, null=True, blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    paid_at = models.DateField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.user) + " purchased " + str(self.resource)

class TransactionType(models.Model):
    # debit & credit
    DEBIT = 0
    CREDIT = 1
    TRANSACTION_TYPES = [
    (DEBIT, 'Debit'),
    (CREDIT, 'Credit'),
    ]
    transaction_type_text = models.IntegerField(choices=TRANSACTION_TYPES)
    def __str__(self):
        return str(self.transaction_type_text)


class TransactionCode(models.Model):
    # we need spread, payout here
    transaction_type = models.ForeignKey(TransactionType, on_delete=models.CASCADE, null=True, blank=True)
    transaction_code_text = models.CharField(max_length=1000)
    def __str__(self):
        return str(self.transaction_code_text)

class Transaction(models.Model):
    description = CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    transaction_code = models.ForeignKey(TransactionCode, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.user) +  str(self.transaction_code) + " transaction  " + "for the amount of " + str(self.amount) + " sats"

class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = PositiveIntegerField(default=0)
    is_locked = models.BooleanField(default=False)
    def __str__(self):
        return str(self.user) + " has a balance of " + str(self.balance)


#need transaction table for withdrawals + payments of users + sats earned + refund
#need erd diagram
#design flows for withdrawal
#minimum fee of 1 sat

class Currency(models.Model):
    text = CharField(max_length=500)
    iso_code = CharField(max_length=3)

    def __str__(self):
        return self.text

app/marketplace/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import UserProfile
from django.core import validators

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['lightning_address', 'bio', 'profile_pic', 'youtube_username', 'tiktok_username', 'twitter_username', 'twitch_username', 'website']

app/marketplace/templates/marketplace/course_detail.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
{{ course.title }}
{% endblock %}

{% block content %}
    <div class="position-relative">
      <!-- Hero -->
      <div class="container content-space-4" >
        <div class="row mb-3">
          <div class="col-md-7 col-lg-8 zi-2">
            <div class="row my-3">
              <div class="col-3">
                <a class="btn-primary btn" href="{% url 'marketplace:discover' %}">Back</a>
              </div>
              
            </div>

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
              {% comment %} <small class="badge bg-success rounded-pill">Bestseller</small>  {% endcomment %}
            <h1>{{ course.title }}</h1>
            <p>{% if course.excerpt %}{{course.excerpt}}{%endif%}</p>
            <div class="d-flex align-items-center flex-wrap">
              <!-- Media -->
              <div class="d-flex align-items-center me-4">
                <div class="flex-shrink-0 avatar-group avatar-group-xs">
                  <span class="avatar avatar-xs avatar-circle">
                    <img class="avatar-img" src="{{course.creator.user_profile.profile_pic.url}}" alt="Image Description">
                  </span>
                </div>
                <div class="flex-grow-1">
                  <span class="ps-2">Created by <a class="link" href="{% url 'marketplace:user-profile' course.creator.username %}">{{course.creator.username}}</a></span>
                </div> 

              </div>
              <!-- End Media -->
            
            </div>
          </div>
          <!-- End Col -->
        </div>
        <!-- End Row -->

      </div>
      <!-- End Hero -->

      <!-- Sidebar -->
      <div class="container content-space-t-md-1 position-md-absolute top-0 start-0 end-0">
        <div class="row justify-content-end">
          <div class="col-md-5 col-lg-4 position-relative zi-2 mb-2 mb-md-0">
            <!-- Sticky Block -->
            <div id="stickyBlockStartPoint">
              <div class="js-sticky-block"
                   data-hs-sticky-block-options='{
                     "parentSelector": "#stickyBlockStartPoint",
                     "breakpoint": "md",
                     "startPoint": "#stickyBlockStartPoint",
                     "endPoint": "#stickyBlockEndPoint",
                     "stickyOffsetTop": 12,
                     "stickyOffsetBottom": 12
                   }'>
                <!-- Card -->
                <div class="card my-9">
                  <div class="p-1">
                    <!-- Fancybox -->
                    <div class="bg-img-start text-center rounded-2 py-10 px-5" style="background-image: url({{course.cover_image.url}});">

                    </div>
                    <!-- End Fancybox -->
                  </div>
                  
                  <!-- Card Body -->
                  <div class="card-body">
                    <div class="mb-3">
                      <span class="card-title h2">{{ course.price }} sats</span>
                       {% comment %} <span class="text-muted"><del>$114.99</del></span>  {% endcomment %}
                    </div>

                    <div class="d-grid mb-2">
                      {% if purchased or course.creator == request.user %}
                      <a class="btn btn-primary btn-transition" href="{% url 'criticalpath:course_detail' course.id %}">View</a>

                      {% else %}
                      <a class="btn btn-primary btn-transition" href="{% url 'marketplace:course_buy' course.id %}">Buy now</a>
                      {% endif %}
                    </div>

                  </div>
                  <!-- End Card Body -->
                </div>
                <!-- End Card -->
              </div>
            </div>
            <!-- End Sticky Block -->
          </div>
        </div>
      </div>
      <!-- End Sidebar -->
    </div>

    <!-- Content -->
    <div class="container content-space-t-1 content-space-t-md-1">
      <div class="row">
      

          <hr class="my-7"> 

           <div class="mb-4">
            <h3>About the instructor</h3>
          </div>

          <div class="row">
            <div class="col-sm-4 mb-4 mb-sm-0">
              <div class="mb-3">
                <img class="avatar avatar-xl avatar-circle" src="{{course.creator.user_profile.profile_pic.url}}" alt="Creator Profile Image">
              </div>
            </div>
            <!-- End Col -->

            <div class="col-sm-8">
              <!-- Info -->
              <div class="mb-2">
                <h4 class="mb-1"><a href="{% url 'marketplace:user-profile' course.creator %}">{{course.creator}}</a></h4>
              </div>

              <p>{{ user_profile.bio }}</p>
              <!-- End Info -->
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row --> 

           
           <div class="border-top pt-7 mt-7">

        </div>

      </div>
    </div>
    <!-- End Content -->
    
    <!-- Sticky Block End Point -->
    <div id="stickyBlockEndPoint"></div>

{% endblock %}

app/marketplace/templates/marketplace/course_success.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
Success!
{% endblock %}

{% block content %}
        
      <div class="container content-space-2 content-space-lg-3">
        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-sm mb-2 mb-sm-0">


              <h2 class="page-header-title">Success!</h2>
            </div>

            <div class="col-sm-auto">
              <a class="btn btn-primary btn-sm" href="{% url 'criticalpath:course_detail' course.id %}">
                <i class="bi-lightning me-1"></i> Start Learning
              </a>
            </div>
          </div>
        </div>
        <!-- End Page Header -->
      
        <div class="row">
            <div class="col">
              <img class="img-fluid rounded-top-2 my-2" src="{% static 'assets/emeralize-2.png' %}" style="max-width: 350px;" alt="Success Image">
                <p class="lead">Your purchase for {{course.title}} was successful. Thank you!</p>
            </div>
        </div>

      </div>
{% endblock%}

app/marketplace/templates/marketplace/ebook_detail.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
{{ebook.title}}
{% endblock %}

{% block content %}
    <div class="position-relative">
      <!-- Hero -->
      <div class="content-space-5" >
        <div class="container">
          <div class="row mb-3">
            <div class="col-md-7 col-lg-8 zi-2">
              <div class="row my-3">
                <div class="col-3">
                  <a class="btn-primary btn" href="{% url 'marketplace:discover' %}">Back</a>
                </div>
                
              </div>

              {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                  <div class="alert alert-info" role="alert">{{ message }}</div>
                  {% endfor %}
              </ul>
            {% endif %}
              <h1>{{ ebook.title }}</h1>
              {% if ebook.excerpt %}<p>{{ ebook.excerpt }}</p>{% endif %}

              <div class="d-flex align-items-center flex-wrap">
                <!-- Media -->
                <div class="d-flex align-items-center me-4">
                  <div class="flex-shrink-0 avatar-group avatar-group-xs">
                    <span class="avatar avatar-xs avatar-circle">
                      <img class="avatar-img" src="{{ebook.creator.user_profile.profile_pic.url}}" alt="Image Description">
                    </span>
                  </div>
                  <div class="flex-grow-1">
                    <span class="ps-2">Created by <a class="link" href="{% url 'marketplace:user-profile' ebook.creator.username %}">{{ebook.creator.username}}</a></span>
                  </div>

                </div>
                <!-- End Media -->

              </div>
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->

        </div>
      </div>
      <!-- End Hero -->

      <!-- Sidebar -->
      <div class="container content-space-t-md-1 position-md-absolute top-0 start-0 end-0">
        <div class="row justify-content-end">
          <div class="col-md-5 col-lg-4 position-relative zi-2 mb-2 mb-md-0">
            <!-- Sticky Block -->
            <div id="stickyBlockStartPoint">
              <div class="js-sticky-block"
                   data-hs-sticky-block-options='{
                     "parentSelector": "#stickyBlockStartPoint",
                     "breakpoint": "md",
                     "startPoint": "#stickyBlockStartPoint",
                     "endPoint": "#stickyBlockEndPoint",
                     "stickyOffsetTop": 12,
                     "stickyOffsetBottom": 12
                   }'>
                <!-- Card -->
                <div class="card my-9">
                  <div class="p-1">
                    <!-- Fancybox -->
                    <div class="bg-img-start text-center rounded-2 py-10 px-5" style="background-image: url({{ebook.cover_image.url}});">

                    </div>
                    <!-- End Fancybox -->
                  </div>
                  
                  <!-- Card Body -->
                  <div class="card-body">
                    <div class="mb-3">
                      <span class="card-title h2">{% if ebook.currency_type.iso_code == "USD"  %} ${% endif %}{{ ebook.price }} {% if ebook.currency_type.iso_code == "SAT" %} sats {% else %} {{ebook.currency_type.iso_code}} {% endif %}</span>
                      {% comment %} <span class="text-muted"><del>$114.99</del></span> {% endcomment %}
                    </div>

                    <div class="d-grid mb-2">
                      {% if purchased or ebook.creator == request.user %}
                      <a class="btn btn-primary btn-transition" href="{% url 'criticalpath:ebook_detail' ebook.id %}">View</a>

                      {% else %}
                      <a class="btn btn-primary btn-transition" href="{% url 'marketplace:ebook_buy' ebook.id %}">Buy now</a>
                      {% endif %}
                    </div>
                  </div>
                  <!-- End Card Body -->
                </div>
                <!-- End Card -->
              </div>
            </div>
            <!-- End Sticky Block -->
          </div>
        </div>
      </div>
      <!-- End Sidebar -->
    </div>

    <!-- Content -->
    <div class="container content-space-t-1 content-space-t-md-1">
      
        </div>
      </div>
    </div>
    <!-- End Content -->

    <!-- Sticky Block End Point -->
    <div id="stickyBlockEndPoint"></div>

{% endblock %}

app/marketplace/templates/marketplace/resource_list.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
Marketplace
{% endblock %}

{% block content %}




    <!-- Card Grid -->
    <div class="container content-space-1 content-space-sm-1">
      <!-- Title -->
      <div class="w-md-75 text-center mx-md-auto mb-9">
        <h2>Resources</h2>
        <p>Check out some of the journeys other users have created. </p>
        {% if user.is_authenticated %}
        <a class="btn btn-danger btn-sm btn-transition" href="{% url 'marketplace:resource_create' %}">Add a Resource</a>
        {% endif %}
      </div>
      <!-- End Title -->
      
      <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 mb-5">
        {% for resource in resources %}
        <div class="col mb-5">
          <!-- Card -->
          <div class="card card-bordered h-100">
            <!-- Card Pinned -->
            <div class="card-pinned">
              <img class="card-img-top" src="{% if resource.cover_image %} {{ resource.cover_image.url }} {% endif %} " alt="Image Description">


            </div>
            <!-- End Card Pinned -->

            <!-- Card Body -->
            <div class="card-body">
              <small class="card-subtitle">{{ resource.category }}</small>

              <div class="mb-3">
                <h3 class="card-title">
                  <a class="text-dark" href="{% url 'marketplace:resource_detail' resource.id %}">{{ resource.title }}</a>
                </h3>
              </div>


            </div>
            <!-- End Card Body -->

            <!-- Card Footer -->
            <div class="card-footer pt-0">
              <div class="d-flex justify-content-between align-items-center">
                <div class="me-2">
                  <h5 class="card-title">{{ resource.price }} sats</h5>
                </div>
                <a class="btn btn-primary btn-sm btn-transition" href="{% url 'marketplace:resource_detail' resource.id %}">Learn More</a>
                {% if user.is_authenticated %}
                <a class="btn btn-success btn-sm btn-transition" href="{% url 'marketplace:resource_buy' resource.id %}">Buy</a>
                {% endif %}
              </div>
            </div>
            <!-- End Card Footer -->
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endfor %}
      </div>
      <!-- End Row -->

    </div>
    <!-- End Card Grid -->

{% endblock %}