app/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# from .forms import CaptchaPasswordResetForm


urlpatterns = [
    path('logout_user/', views.logout_view, name="logout_user"),
    path('register_user/', views.register_user, name="register"),
    path('help/', views.help, name="help"),
    path('password/', views.change_password, name='change_password'),
    path('logout_user/', views.logout_view, name="logout_user"),
    path('signin/', views.login_user, name="signin"),
    path("password_reset/", auth_views.PasswordResetView.as_view()),

    # path("password_reset/", auth_views.PasswordResetView.as_view(form_class=CaptchaPasswordResetForm)),

] 

app/criticalpath/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings


from . import views

app_name='criticalpath'
urlpatterns = [
    path('journeys/', views.journey_list, name='journey_list'),
    path('my-criticalpath/', views.UserCriticalPathDetailView.as_view(), name='my-criticalpath'),
    # path('my-saved-journeys', views.UserSavedJourneysListView.as_view(), name='my-saved-journeys'),
    # path('journey/<int:pk>/', views.JourneyDetailView.as_view(), name='journey_detail'),
    # path('journey/create/',
    #     views.JourneyCreateView.as_view(success_url=reverse_lazy('criticalpath:phase_create')), name='journey_create'),
    # path('journey/<int:pk>/update/',
    #     views.JourneyUpdateView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_update'),
    # path('journey/<int:pk>/delete/',
    #     views.JourneyDeleteView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_delete'),
    # path('journey/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    # path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy('journey_list')), name='comment_delete'),
    # path('journey/<int:pk>/favorite',
    #     views.AddFavoriteView.as_view(), name='journey_favorite'),
    # path('journey/<int:pk>/unfavorite',
    #     views.DeleteFavoriteView.as_view(), name='journey_unfavorite'),
    # path('journey/<int:journey_pk>/resource/', views.ResourceAddView.as_view(success_url=reverse_lazy('criticalpath:journey_detail')), name='resource_add'),

    path('resource/create/', views.ResourceCreateView.as_view(success_url=reverse_lazy('home')), name='resource_create'),
    path('resource/<int:resource_pk>/', views.ResourceDetailView.as_view(), name='resource_detail'),
    path('resource/<int:resource_pk>/update/', views.ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/<int:resource_pk>/delete/', views.ResourceDeleteView.as_view(), name='resource_delete'),

    path('ebook/create/', views.EbookCreateView.as_view(success_url=reverse_lazy('home')), name='ebook_create'),
    path('ebook/<int:ebook_pk>/splits/', views.EbookPaymentSplitsView.as_view(), name='ebook_add_splits'),
    path('ebook/<int:ebook_pk>/', views.EbookDetailView.as_view(), name='ebook_detail'),
    path('ebook/<int:ebook_pk>/update/', views.EbookUpdateView.as_view(), name='ebook_update'),
    path('ebook/<int:ebook_pk>/delete/', views.EbookDeleteView.as_view(), name='ebook_delete'),

    path('workshop/create/', views.WorkshopCreateView.as_view(success_url=reverse_lazy('home')), name='workshop_create'),
    path('workshop/<int:workshop_pk>/splits/', views.WorkshopPaymentSplitsView.as_view(), name='workshop_add_splits'),
    path('workshop/<int:workshop_pk>/', views.WorkshopDetailView.as_view(), name='workshop_detail'),
    path('workshop/<int:workshop_pk>/update/', views.WorkshopUpdateView.as_view(), name='workshop_update'),
    path('workshop/<int:workshop_pk>/delete/', views.WorkshopDeleteView.as_view(), name='workshop_delete'),

    path('course/create/', views.CourseCreateView.as_view(success_url=reverse_lazy('criticalpath:creator')), name='course_create'),
    path('course/<int:course_pk>/add/', views.CourseAddResourcesView.as_view(), name='course_add_resources'),
    path('course/<int:course_pk>/splits/', views.CoursePaymentSplitsView.as_view(), name='course_add_splits'),
    path('course/<int:course_pk>/resource/<int:resource_pk>/', views.CourseResourceDetailView.as_view(), name='course_resource_detail'),
    path('course/<int:course_pk>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('course/<int:course_pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course/<int:course_pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),



    path('creator/', views.creation_list, name="my-creations"),
    path('creator/signup/', views.creator_signup, name="creator_signup"),

    # uncomment if you want to enable rewards
    # path('course/<int:course_pk>/resource/<int:resource_pk>/reward/', views.reward_user, name="resource_reward_user"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/emeralize/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy, include
from marketplace.views import homepage
from marketplace import views
from accounts.views import confirm
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from django_email_verification import urls as email_urls  # include the urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="home"),
    path('', include('marketplace.urls')),
    path('', include('criticalpath.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(email_urls)),  # connect them to an arbitrary path
    # path('email/<str:token>/', confirm), # remember to set the "token" parameter in the url!


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "marketplace.views.handle_not_found"

# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL,  
                        document_root=settings.MEDIA_ROOT) 

app/marketplace/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from marketplace import views
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static


app_name='marketplace'
urlpatterns = [
    path('marketplace/', discover, name='discover'),
    path('marketplace/resources/', resource_list, name='resource_list'),
    path('journey/<int:pk>/buy/', journey_buy_view, name="journey_buy"),

    path('resource/<int:pk>/buy/', resource_buy_view, name="resource_buy"),
    path('resource/purchase_detail/<int:pk>/', views.ResourcePurchaseDetailView.as_view(), name="resource_purchase_detail"),
    path('resource/<int:resource>/buy/success/', resource_success, name="resource_success"),

    path('ebook/<int:pk>/buy/', ebook_buy_view, name="ebook_buy"),
    path('ebook/purchase_detail/<int:pk>/', views.EbookPurchaseDetailView.as_view(), name="ebook_purchase_detail"),
    path('ebook/<int:ebook>/buy/success/', ebook_success, name="ebook_success"),

    path('workshop/<int:pk>/buy/', workshop_buy_view, name="workshop_buy"),
    path('workshop/purchase_detail/<int:pk>/', views.WorkshopPurchaseDetailView.as_view(), name="workshop_purchase_detail"),
    path('workshop/<int:workshop>/buy/success/', workshop_success, name="workshop_success"),

    path('course/purchase_detail/<int:pk>/', views.CoursePurchaseDetailView.as_view(), name="course_purchase_detail"),
    path('course/<int:pk>/buy/', course_buy_view, name="course_buy"),
    path('course/<int:course>/buy/success/', course_success, name="course_success"),

    path('journey/<int:journey>/buy/success/', journey_success, name="journey_success"),
    path('webhook/zbd/', csrf_exempt(zbd_webhook), name="charge_callback"),
    path('charge-status/', charge_status_check),
    path('purchase-history/', purchase_history, name="purchase-history"),
    path('transaction-history/', transaction_history, name="transaction-history"),
    path('accounts/profile/', views.UserProfileCreate.as_view(), name="account-profile"),
    path('profile/<username>/', profile, name="user-profile"),
    path('profile/<username>/tip/', tip_amount, name="tip-amount"),
    path('profile/<username>/tip/pay/', tip_pay, name="tip-pay"),
    path('profile/<username>/tip/pay/success/', tip_success, name="tip-success"),
    path('wallet/', wallet_view, name="wallet"),
    path('withdrawal/', withdrawal, name="withdrawal"),
    path('terms/', terms, name="terms"),
    path('privacy/', privacy, name="privacy"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

User._meta.get_field('email')._unique = True

app/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User
from django import forms
# from captcha.fields import ReCaptchaField



class RegisterUserForm(UserCreationForm):
    email = forms.EmailField()
    # captcha = ReCaptchaField()
    

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

# class CaptchaPasswordResetForm(PasswordResetForm):
#     captcha = ReCaptchaField()



# class CaptchaForm(forms.Form):
#     captcha = ReCaptchaField()

app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from .forms import RegisterUserForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django_email_verification import send_email, verify_view, verify_token
from django.contrib.auth.models import User

# Create your views here.
def help(request):
    if request.method == "GET":
        return render(request, 'accounts/help.html', {})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        # form = CaptchaForm(request.POST)
        # if not form.is_valid():
        #     messages.error(request, ("Invalid captcha sign-up."))
        #     return redirect(reverse_lazy('signin'))
        
        is_active_user = User.objects.all().filter(username=username)
        if len(is_active_user) == 1:
            for user in is_active_user:
                check_pass = user.check_password(password)
                if not user.is_active and check_pass:
                    print(user.is_active)
                    send_email(user)
                    messages.success(request, ("Please verify your email."))
                    return redirect(reverse_lazy('signin'))

        user = authenticate(request, username=username, password=password)

                
        if user is None:
            messages.success(request, ("Invalid email or password."))
        
            return redirect(reverse_lazy('signin'))

        is_active_user = User.objects.get(username=username)



        login(request, user)
        return redirect(reverse_lazy('home'))
        

        




    else:
        # context = {"form" : CaptchaForm}
        return render(request, 'registration/login.html')

def logout_view(request):
    logout(request)
    return redirect(reverse_lazy('home'))

def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():

            user = form.save()
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # user = authenticate(username=username, password=password)
            # login (request, user)
            user.is_active = False  # Example
            send_email(user)
            messages.success(request, ("Registration successful. Please verify your email."))
            return redirect(reverse_lazy('signin'))
        messages.error(request, "Unsuccessful registration. Invalid information.")
        return render(request, 'accounts/signup.html', {'form':form})
    else:
        form = RegisterUserForm()
        return render(request, 'accounts/signup.html', {'form':form})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
            return redirect('change_password')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

def confirm(request, token):
    success, user = verify_token(token)
    return HttpResponse(f'Account verified, {user.username}' if success else 'Invalid token')

app/accounts/templates/accounts/base.html
{% extends "emeralize/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Form
{% endblock %}
{% block content %}
        
      <div class="container content-space-2 content-space-lg-3 mt-5 mb-5">
        <div class="row">
          <div class="col-12">
              {% if messages %}
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
              {% endif %}
              <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-primary" type="submit" value="Submit">
                <input class="btn btn-primary" type="submit" onclick="window.location='{% url 'home' %}' ; return false;" value="Cancel">
              </form>
          </div>
        </div>
      </div>
{% endblock %}

app/accounts/templates/accounts/change_password.html
{% extends "emeralize/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Change Password
{% endblock %}
{% block content %}
        
      <div class="container content-space-1 content-space-sm-1 mt-5 mb-5">
        <div class="row">
          <div class="col-12">
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">

            There was an error with your form.

            </div>
            {% endif %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
            <img class="img-fluid rounded-top-2 my-2" src="{% static 'assets/emeralize-1.png' %}" style="max-width: 350px;" alt="Success Image">
            <h1>Change Password</h1>
            <p>Please fill out the form below to change your password.</p>

            <form action="{% url 'change_password' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary btn-transition">Save</button>

            </form>
          </div>
        </div>
      </div>
{% endblock %}

app/accounts/templates/accounts/help.html
{% extends "emeralize/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Help and Support
{% endblock %}
{% block content %}
        
      <div class="container content-space-1 content-space-sm-1 mt-9 mb-5">
        <div class="row">
          <div class="col-12">
            <h1>Help and Support</h1>
            <p>Need some help? Reach out to us with your questions and get assistance</p>
            <a href="https://forms.gle/5kQuez3UQU5SFczj6" target="_blank" class="btn btn-primary btn-transition">Reach Out</a>
            <a href="https://discord.gg/pmuu6UyQ" target="_blank" class="btn btn-outline-primary"><i class="bi bi-discord"></i> Join our Discord</a>
          </div>
        </div>
      </div>
{% endblock %}

app/accounts/templates/accounts/profile.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
{{educator.username}}
{% endblock %}

{% block content %}
<!-- Content -->
<div class="container content-space-1 content-space-sm-1">


  <div class="row my-9 ">
    <div class="col-12 text-center">
      <h3>About {{educator.username}}</h3>
      <p>{{educator_profile.bio}}</p>
    </div>
    <div class="col-12 text-center">
      <div class="mb-3">
        <img class="avatar avatar-xl avatar-circle" src="{{educator_profile.profile_pic.url}}" alt="Image Description">
      </div>
      <ul class="list-unstyled list-py-1">        
        <li>
          {% if educator_profile.website %}
          <a class="btn btn-outline-primary"  href="{{educator_profile.website}}">
            <i class="bi bi-globe"></i>
          </a>
          {% endif %}        
          {% if educator_profile.tiktok_username %}
          <a target="_blank" class="btn btn-outline-primary"  href="https://tiktok.com/@{{educator_profile.tiktok_username}}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="20" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
              <path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3V0Z"/>
            </svg>
          </a>
          {% endif %}
          {% if educator_profile.youtube_username %}
          <a target="_blank" class="btn btn-outline-primary"  href="https://www.youtube.com/channel/{{educator_profile.youtube_username}}">
            <i class="bi bi-youtube"></i>
          </a>
          {% endif %}
          {% if educator_profile.twitter_username %}
          <a target="_blank" class="btn btn-outline-primary" href="https://twitter.com/{{educator_profile.twitter_username}}">
            <i class="bi bi-twitter"></i>
          </a>
          
          {% endif %}
          {% if educator_profile.twitch_username %}
          <a target="_blank" class="btn btn-outline-primary"  href="https://twitch.tv/{{educator_profile.twitch_username}}">
            <i class="bi bi-twitch"></i>
          </a>
          
          {% endif %}
          {% if educator_profile.bitcointv_username %}
          <a target="_blank" href="https://bitcointv.com/c/{{educator_profile.bitcointv_username}}/videos">
            <i class="bi bi-tv"></i>
          </a>
          {% endif %}

        </li>
        {% if request.user == educator %}
        <li><a class="btn btn-outline-primary btn-transition" href="{% url 'marketplace:account-profile' %}">Edit Profile</a></li>
        {% else %}
        <li><a class="btn btn-primary btn-transition" href="{% url 'marketplace:tip-amount' educator.username %}">Tip</a></li>
        {% endif %}

      </ul>
    </div>
    <!-- End Col -->

    <div class="col-sm-8 text-center">
      <!-- Info -->
      <div class="mb-2">
        <h4 class="mb-1">{% if profile.verified %}<i class="bi bi-patch-check-fill"></i>{% endif %}</h4>
      </div>

      <p>{{profile.bio}}</p>
      <!-- End Info -->
    </div>
    <!-- End Col -->
    {% if creator_courses %}
    <div class="col-12">
      <div class="border-top">
        <div class="my-4">
          <h4 class="text-center">Courses by {{educator.username}}</h4>
        </div>
        <div class="border-top">

        <div class="row mt-7">
          {% for course in creator_courses %}
            <div class="col-md-6 col-lg-3 mb-5">
              <!-- Card -->
              <div class="card card-bordered h-100">
                <!-- Card Pinned -->
                <div class="card-pinned">
                  <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if course.cover_image %} {{ course.cover_image.url }} {% endif %} " alt="Image Description">

                </div>
                <!-- End Card Pinned -->

                <!-- Card Body -->
                <div class="card-body">

                  <div class="mb-3">
                    <h3 class="card-title">
                      <a class="text-dark" href="{% url 'criticalpath:course_detail' course.id %}">{{ course.title }}</a>
                    </h3>
                  </div>

                </div>
                <!-- End Card Body -->

                <!-- Card Footer -->
                <div class="card-footer pt-0">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="me-9">
                      <span class="d-block small">{{ course.price }} sats</span>
                    </div>
                    {% if course.price == 0 %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:course_detail' course.id %}">View</a>
                    {% else %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'marketplace:course_purchase_detail' course.id %}">View</a>
                    {% endif %}
                  </div>
                </div>
                <!-- End Card Footer -->
              </div>
              <!-- End Card -->
            </div>
            <!-- End Col -->
          {% endfor %}
        </div>

        {% comment %} <div class="text-end small">
          <a class="link" href="../demo-course/courses.html">See all courses <i class="bi-chevron-right small ms-1"></i></a>
        </div> {% endcomment %}
      </div>
    </div>
    {%endif %}

    {% if creator_workshops %}
    <div class="col-12">
      <div class="border-top">
        <div class="my-4">
          <h4 class="text-center">Workshops by {{educator.username}}</h4>
        </div>
        <div class="border-top">

        <div class="row mt-7">
          {% for workshop in creator_workshop %}
            <div class="col-md-6 col-lg-3 mb-5">
              <!-- Card -->
              <div class="card card-bordered h-100">
                <!-- Card Pinned -->
                <div class="card-pinned">
                  <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if workshop.cover_image %} {{ workshop.cover_image.url }} {% endif %} " alt="Image Description">

                </div>
                <!-- End Card Pinned -->

                <!-- Card Body -->
                <div class="card-body">

                  <div class="mb-3">
                    <h3 class="card-title">
                      <a class="text-dark" href="{% url 'criticalpath:workshop_detail' workshop.id %}">{{ workshop.title }}</a>
                    </h3>
                  </div>

                </div>
                <!-- End Card Body -->

                <!-- Card Footer -->
                <div class="card-footer pt-0">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="me-9">
                      <span class="d-block small">{% if workshop.currency_type.iso_code == "USD" %} ${% endif %}{{ workshop.price }} {% if workshop.currency_type.iso_code == "SAT" %} sats {% else %} {{workshop.currency_type.iso_code}} {% endif %}</span>
                    </div>
                    {% if workshop.price == 0 %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:workshop_detail' workshop.id %}">View</a>
                    {% else %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'marketplace:workshop_purchase_detail' workshop.id %}">View</a>
                    {% endif %}
                  </div>
                </div>
                <!-- End Card Footer -->
              </div>
              <!-- End Card -->
            </div>
            <!-- End Col -->
          {% endfor %}
        </div>

        {% comment %} <div class="text-end small">
          <a class="link" href="../demo-course/courses.html">See all courses <i class="bi-chevron-right small ms-1"></i></a>
        </div> {% endcomment %}
      </div>
    </div>
    {%endif %}

    {% if creator_ebooks %}
    <div class="col-12">
      <div class="border-top">
        <div class="my-4">
          <h4 class="text-center">Ebooks by {{educator.username}}</h4>
        </div>
        <div class="border-top">

        <div class="row mt-7">
          {% for ebook in creator_ebooks %}
            <div class="col-md-6 col-lg-3 mb-5">
              <!-- Card -->
              <div class="card card-bordered h-100">
                <!-- Card Pinned -->
                <div class="card-pinned">
                  <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if ebook.cover_image %} {{ ebook.cover_image.url }} {% endif %} " alt="Image Description">

                </div>
                <!-- End Card Pinned -->

                <!-- Card Body -->
                <div class="card-body">

                  <div class="mb-3">
                    <h3 class="card-title">
                      <a class="text-dark" href="{% url 'criticalpath:ebook_detail' ebook.id %}">{{ ebook.title }}</a>
                    </h3>
                  </div>

                </div>
                <!-- End Card Body -->

                <!-- Card Footer -->
                <div class="card-footer pt-0">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="me-9">
                      <span class="d-block small">{% if ebook.currency_type.iso_code == "USD" %} ${% endif %}{{ ebook.price }} {% if ebook.currency_type.iso_code == "SAT" %} sats {% else %} {{ebook.currency_type.iso_code}} {% endif %}</span>
                    </div>
                    {% if ebook.price == 0 %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:ebook_detail' ebook.id %}">View</a>
                    {% else %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'marketplace:ebook_purchase_detail' ebook.id %}">View</a>
                    {% endif %}
                  </div>
                </div>
                <!-- End Card Footer -->
              </div>
              <!-- End Card -->
            </div>
            <!-- End Col -->
          {% endfor %}
        </div>

        {% comment %} <div class="text-end small">
          <a class="link" href="../demo-course/courses.html">See all courses <i class="bi-chevron-right small ms-1"></i></a>
        </div> {% endcomment %}
      </div>
    </div>
    {%endif %}

    {% if creator_resources %}
    <div class="col-12">
      <div class="border-top">
        <div class="my-4">
          <h4 class="text-center">Resources by {{educator.username}}</h4>
        </div>
        <div class="border-top">

        <div class="row mt-7">
          {% for resource in creator_resources %}
            <div class="col-md-6 col-lg-3 mb-5">
              <!-- Card -->
              <div class="card card-bordered h-100">
                <!-- Card Pinned -->
                <div class="card-pinned">
                  <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if resource.cover_image %} {{ resource.cover_image.url }} {% endif %} " alt="Image Description">

                </div>
                <!-- End Card Pinned -->

                <!-- Card Body -->
                <div class="card-body">

                  <div class="mb-3">
                    <h3 class="card-title">
                      <a class="text-dark" href="{% url 'criticalpath:resource_detail' resource.id %}">{{ resource.title }}</a>
                    </h3>
                  </div>

                </div>
                <!-- End Card Body -->

                <!-- Card Footer -->
                <div class="card-footer pt-0">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="me-9">
                      <span class="d-block small">{{ resource.price }} sats</span>
                    </div>
                    {% if resource.price == 0 %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:resource_detail' resource.id %}">View</a>
                    {% else %}
                    <a class="btn btn-primary btn-sm btn-transition" href="{% url 'marketplace:resource_purchase_detail' resource.id %}">View</a>
                    {% endif %}
                  </div>
                </div>
                <!-- End Card Footer -->
              </div>
              <!-- End Card -->
            </div>
            <!-- End Col -->
          {% endfor %}
        </div>

      </div>
    </div>
    {%endif %}


  </div>
  <!-- End Row -->

  
</div>
<!-- End Content -->






{% endblock%}

app/accounts/templates/accounts/signup.html
{% extends "emeralize/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Sign Up
{% endblock %}
{% block content %}
        
      <div class="container content-space-1 content-space-sm-1 mt-5 mb-5">
        <div class="row">
          <div class="col-12">
            <img class="img-fluid rounded-top-2 my-2" src="{% static 'assets/emeralize-4.png' %}" style="max-width: 350px;" alt="Success Image">

            <h1>Sign Up</h1>
            <p>Start purchasing resources and learning by creating an account</p>
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">

            There was an error with your form.

            </div>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="{% url 'register' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type='submit'>Submit</button>
                <div class="my-3">Already have an account? <a href="{% url 'signin' %}">Sign In</a>.</div>
            </form>
          </div>
        </div>
      </div>
{% endblock %}