app/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# from .forms import CaptchaPasswordResetForm


urlpatterns = [
    path('logout_user/', views.logout_view, name="logout_user"),
    path('register_user/', views.register_user, name="register"),
    path('help/', views.help, name="help"),
    path('password/', views.change_password, name='change_password'),
    path('logout_user/', views.logout_view, name="logout_user"),
    path('signin/', views.login_user, name="signin"),
    path("password_reset/", auth_views.PasswordResetView.as_view()),

    # path("password_reset/", auth_views.PasswordResetView.as_view(form_class=CaptchaPasswordResetForm)),

] 

app/criticalpath/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings


from . import views

app_name='criticalpath'
urlpatterns = [
    path('journeys/', views.journey_list, name='journey_list'),
    path('my-criticalpath/', views.UserCriticalPathDetailView.as_view(), name='my-criticalpath'),
    # path('my-saved-journeys', views.UserSavedJourneysListView.as_view(), name='my-saved-journeys'),
    # path('journey/<int:pk>/', views.JourneyDetailView.as_view(), name='journey_detail'),
    # path('journey/create/',
    #     views.JourneyCreateView.as_view(success_url=reverse_lazy('criticalpath:phase_create')), name='journey_create'),
    # path('journey/<int:pk>/update/',
    #     views.JourneyUpdateView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_update'),
    # path('journey/<int:pk>/delete/',
    #     views.JourneyDeleteView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_delete'),
    # path('journey/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    # path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy('journey_list')), name='comment_delete'),
    # path('journey/<int:pk>/favorite',
    #     views.AddFavoriteView.as_view(), name='journey_favorite'),
    # path('journey/<int:pk>/unfavorite',
    #     views.DeleteFavoriteView.as_view(), name='journey_unfavorite'),
    # path('journey/<int:journey_pk>/resource/', views.ResourceAddView.as_view(success_url=reverse_lazy('criticalpath:journey_detail')), name='resource_add'),

    path('resource/create/', views.ResourceCreateView.as_view(success_url=reverse_lazy('home')), name='resource_create'),
    path('resource/<int:resource_pk>/', views.ResourceDetailView.as_view(), name='resource_detail'),
    path('resource/<int:resource_pk>/update/', views.ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/<int:resource_pk>/delete/', views.ResourceDeleteView.as_view(), name='resource_delete'),

    path('ebook/create/', views.EbookCreateView.as_view(success_url=reverse_lazy('home')), name='ebook_create'),
    path('ebook/<int:ebook_pk>/splits/', views.EbookPaymentSplitsView.as_view(), name='ebook_add_splits'),
    path('ebook/<int:ebook_pk>/', views.EbookDetailView.as_view(), name='ebook_detail'),
    path('ebook/<int:ebook_pk>/update/', views.EbookUpdateView.as_view(), name='ebook_update'),
    path('ebook/<int:ebook_pk>/delete/', views.EbookDeleteView.as_view(), name='ebook_delete'),

    path('workshop/create/', views.WorkshopCreateView.as_view(success_url=reverse_lazy('home')), name='workshop_create'),
    path('workshop/<int:workshop_pk>/splits/', views.WorkshopPaymentSplitsView.as_view(), name='workshop_add_splits'),
    path('workshop/<int:workshop_pk>/', views.WorkshopDetailView.as_view(), name='workshop_detail'),
    path('workshop/<int:workshop_pk>/update/', views.WorkshopUpdateView.as_view(), name='workshop_update'),
    path('workshop/<int:workshop_pk>/delete/', views.WorkshopDeleteView.as_view(), name='workshop_delete'),

    path('course/create/', views.CourseCreateView.as_view(success_url=reverse_lazy('criticalpath:creator')), name='course_create'),
    path('course/<int:course_pk>/add/', views.CourseAddResourcesView.as_view(), name='course_add_resources'),
    path('course/<int:course_pk>/splits/', views.CoursePaymentSplitsView.as_view(), name='course_add_splits'),
    path('course/<int:course_pk>/resource/<int:resource_pk>/', views.CourseResourceDetailView.as_view(), name='course_resource_detail'),
    path('course/<int:course_pk>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('course/<int:course_pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course/<int:course_pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),



    path('creator/', views.creation_list, name="my-creations"),
    path('creator/signup/', views.creator_signup, name="creator_signup"),

    # uncomment if you want to enable rewards
    # path('course/<int:course_pk>/resource/<int:resource_pk>/reward/', views.reward_user, name="resource_reward_user"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/emeralize/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy, include
from marketplace.views import homepage
from marketplace import views
from accounts.views import confirm
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from django_email_verification import urls as email_urls  # include the urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="home"),
    path('', include('marketplace.urls')),
    path('', include('criticalpath.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(email_urls)),  # connect them to an arbitrary path
    # path('email/<str:token>/', confirm), # remember to set the "token" parameter in the url!


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "marketplace.views.handle_not_found"

# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL,  
                        document_root=settings.MEDIA_ROOT) 

app/marketplace/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from marketplace import views
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static


app_name='marketplace'
urlpatterns = [
    path('marketplace/', discover, name='discover'),
    path('marketplace/resources/', resource_list, name='resource_list'),
    path('journey/<int:pk>/buy/', journey_buy_view, name="journey_buy"),

    path('resource/<int:pk>/buy/', resource_buy_view, name="resource_buy"),
    path('resource/purchase_detail/<int:pk>/', views.ResourcePurchaseDetailView.as_view(), name="resource_purchase_detail"),
    path('resource/<int:resource>/buy/success/', resource_success, name="resource_success"),

    path('ebook/<int:pk>/buy/', ebook_buy_view, name="ebook_buy"),
    path('ebook/purchase_detail/<int:pk>/', views.EbookPurchaseDetailView.as_view(), name="ebook_purchase_detail"),
    path('ebook/<int:ebook>/buy/success/', ebook_success, name="ebook_success"),

    path('workshop/<int:pk>/buy/', workshop_buy_view, name="workshop_buy"),
    path('workshop/purchase_detail/<int:pk>/', views.WorkshopPurchaseDetailView.as_view(), name="workshop_purchase_detail"),
    path('workshop/<int:workshop>/buy/success/', workshop_success, name="workshop_success"),

    path('course/purchase_detail/<int:pk>/', views.CoursePurchaseDetailView.as_view(), name="course_purchase_detail"),
    path('course/<int:pk>/buy/', course_buy_view, name="course_buy"),
    path('course/<int:course>/buy/success/', course_success, name="course_success"),

    path('journey/<int:journey>/buy/success/', journey_success, name="journey_success"),
    path('webhook/zbd/', csrf_exempt(zbd_webhook), name="charge_callback"),
    path('charge-status/', charge_status_check),
    path('purchase-history/', purchase_history, name="purchase-history"),
    path('transaction-history/', transaction_history, name="transaction-history"),
    path('accounts/profile/', views.UserProfileCreate.as_view(), name="account-profile"),
    path('profile/<username>/', profile, name="user-profile"),
    path('profile/<username>/tip/', tip_amount, name="tip-amount"),
    path('profile/<username>/tip/pay/', tip_pay, name="tip-pay"),
    path('profile/<username>/tip/pay/success/', tip_success, name="tip-success"),
    path('wallet/', wallet_view, name="wallet"),
    path('withdrawal/', withdrawal, name="withdrawal"),
    path('terms/', terms, name="terms"),
    path('privacy/', privacy, name="privacy"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/criticalpath/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from django.core import validators
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from criticalpath.humanize import naturalsize
from django.forms import ModelForm, Select
from captcha.fields import ReCaptchaField


from marketplace.models import UserProfile
from django.core import validators

class CreatorSignUpForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['creator']

class JourneyForm(ModelForm):
    class Meta:
        model = Journey
        fields = ['title', 'objective', 'category', 'price', 'cover_image']


class CourseForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Course
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price' ]

class CourseAddResourcesForm(ModelForm):
    class Meta:
        model = CourseResources
        fields = ['resource', 'order_no' ]

class CoursePaymentSplitsForm(ModelForm):
    class Meta:
        model = CoursePaymentSplits
        fields = ['user', 'amount' ]

# class PhaseForm(ModelForm):
#     class Meta:
#         model = Phase
#         fields = ['title', 'description']

class EbookForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Ebook
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'currency_type', 'file', 'content' ]

class EbookPaymentSplitsForm(ModelForm):
    class Meta:
        model = EbookPaymentSplits
        fields = ['user', 'amount' ]

class WorkshopForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Workshop
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'currency_type', 'content' ]

class WorkshopPaymentSplitsForm(ModelForm):
    class Meta:
        model = WorkshopPaymentSplits
        fields = ['user', 'amount' ]


class ResourceForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Resource
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'content' ]


class SuperResourceForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Resource
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'content', 'file', 'video']


class AddResourceForm(ModelForm):
    class Meta:
        model = JourneyResources
        fields = ['resource']


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)


# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

app/criticalpath/templates/criticalpath/confirm_delete.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
Delete {{resource.title}}
{% endblock %}
{% block content %}
<div class="container content-space-2 content-space-lg-3">
    <div class="row">
        <div class="col-12">
          <h1>Delete 
          {% if resource %} {{resource.title}} {% endif %}
          {% if course %} {{course.title}} {% endif %}
        </h1>
        
        <p>Are you sure you want to delete the 
          {% if resource %} Resource : {{ resource.title }}?{% endif %}
          {% if course %} Course : {{ course.title }}?{% endif %}
        </p>
        
        <form action="" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit" >Yes Delete.</button>
          
          <input class="btn btn-primary" type="submit" value="Cancel" onclick="window.location.href='{% url 'criticalpath:my-creations' %}';return false;">
        </form>

        </div>
    </div>
</div>

{% endblock %}

app/criticalpath/templates/criticalpath/creator.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
Creator
{% endblock %}

{% block content %}

   

    {% if creator_profile.creator %}
    <!-- Card Grid -->
    <div class="container content-space-1 content-space-sm-1">

      

      <!-- Title -->

      
      <div class="row mt-9">
        <div class="col-12 mb-5">
          <h1>✨ Creator</h1>
          <p>Create new things and share them our marketplace for potential sats</p>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <div class="alert alert-info" role="alert">{{ message }}</div>
              {% endfor %}
          </ul>
          {% endif %}
        <div class="w-md-75 my-5">
          <h2>Resources</h2>
          <p>Resources are single pieces of content like a blog, video, audio, or all of the above. </p>
          <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:resource_create' %}">Add</a>
        </div>

        </div>
      </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 mb-5">
        <!-- End Title -->

        {% for resource in resources %}
        <div class="col-md-6 col-lg-3 mb-5">
          <!-- Card -->
          <div class="card card-bordered h-100">
            <!-- Card Pinned -->
            <div class="card-pinned">
              <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if resource.cover_image %} {{ resource.cover_image.url }} {% endif %} " alt="Image Description">

              
            </div>
            <!-- End Card Pinned -->

            <!-- Card Body -->
            <div class="card-body">

              <div class="mb-3">
                <h3 class="card-title">
                  <a class="text-dark" href="{% url 'criticalpath:resource_detail' resource.id %}">{{ resource.title }}</a>
                </h3>
              </div>


            </div>
            <!-- End Card Body -->

            <!-- Card Footer -->
            <div class="card-footer pt-0">
              <div class="d-flex justify-content-between align-items-center">
                <div class="me-2">
                  <h5 class="card-title">{{ resource.price }} sats</h5>
                </div>
                <a class="btn btn-outline-primary btn-sm btn-transition" href="{% url 'criticalpath:resource_update' resource.id %}">Edit</a>
                <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:resource_detail' resource.id %}">View</a>
              </div>
            </div>
            <!-- End Card Footer -->
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endfor %}


      </div>
      <div class="row mt-9">

        <div class="w-md-75 my-5">
          <h2>Courses</h2>
          <p>Courses are sets of resources that are organized in a way to help learners learn a topic from A-to-Z. </p>
          <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:course_create' %}">Add</a>
        </div>
      </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 mb-5">


        <!-- End Title -->
        {% for course in courses %}
        <div class="col-md-6 col-lg-4 mb-5">
          <!-- Card -->
          <div class="card card-bordered h-100">
            <!-- Card Pinned -->
            <div class="card-pinned">
              <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if course.cover_image %} {{ course.cover_image.url }} {% endif %} " alt="Image Description">

            </div>
            <!-- End Card Pinned -->

            <!-- Card Body -->
            <div class="card-body">

              <div class="mb-3">
                <h3 class="card-title">
                  <a class="text-dark" href="{% url 'criticalpath:course_detail' course.id %}">{{ course.title }}</a>
                </h3>
              </div>


            </div>
            <!-- End Card Body -->

            <!-- Card Footer -->
            <div class="card-footer pt-0">
              <div class="d-flex justify-content-between align-items-center">
                <div class="me-2">
                  <h5 class="card-title">{{ course.price }} sats</h5>
                </div>
                <a class="btn btn-outline-primary btn-sm btn-transition" href="{% url 'criticalpath:course_update' course.id %}">Edit</a>
                <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:course_detail' course.id %}">View</a>
              </div>
            </div>
            <!-- End Card Footer -->
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endfor %}
      </div>
      <!-- End Row -->

      <div class="row mt-9">

        <div class="w-md-75 my-5">
          <h2>Workshops</h2>
          <p>Show someone how to do something cool. </p>
          <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:workshop_create' %}">Add</a>
        </div>
      </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 mb-5">


        <!-- End Title -->
        {% for workshop in workshops %}
        <div class="col-md-6 col-lg-4 mb-5">
          <!-- Card -->
          <div class="card card-bordered h-100">
            <!-- Card Pinned -->
            <div class="card-pinned">
              <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if workshop.cover_image %} {{ workshop.cover_image.url }} {% endif %} " alt="Image Description">

              
            </div>
            <!-- End Card Pinned -->

            <!-- Card Body -->
            <div class="card-body">

              <div class="mb-3">
                <h3 class="card-title">
                  <a class="text-dark" href="{% url 'criticalpath:workshop_detail' workshop.id %}">{{ workshop.title }}</a>
                </h3>
              </div>


            </div>
            <!-- End Card Body -->

            <!-- Card Footer -->
            <div class="card-footer pt-0">
              <div class="d-flex justify-content-between align-items-center">
                <div class="me-2">
                  <h5 class="card-title">{% if workshop.currency_type.iso_code == "USD"  %} ${% endif %}{{ workshop.price }} {% if workshop.currency_type.iso_code == "SAT" %} sats {% else %} {{workshop.currency_type.iso_code}} {% endif %}</h5>
                </div>
                <a class="btn btn-outline-primary btn-sm btn-transition" href="{% url 'criticalpath:workshop_update' workshop.id %}">Edit</a>
                <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:workshop_detail' workshop.id %}">View</a>
              </div>
            </div>
            <!-- End Card Footer -->
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endfor %}
      </div>
      <!-- End Row -->

      <div class="row mt-9">

        <div class="w-md-75 my-5">
          <h2>Ebooks</h2>
          <p>Sell your awesome books and keep 38%-58% more. </p>
          <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:ebook_create' %}">Add</a>
        </div>
      </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 mb-5">


        <!-- End Title -->
        {% for ebook in ebooks %}
        <div class="col-md-6 col-lg-4 mb-5">
          <!-- Card -->
          <div class="card card-bordered h-100">
            <!-- Card Pinned -->
            <div class="card-pinned">
              <img class="card-img-top" style="object-fit: cover; overflow:hidden !important; width: 100% !important; max-width: 100% !important; max-height: 100%;" src="{% if ebook.cover_image %} {{ ebook.cover_image.url }} {% endif %} " alt="Image Description">

            </div>
            <!-- End Card Pinned -->

            <!-- Card Body -->
            <div class="card-body">

              <div class="mb-3">
                <h3 class="card-title">
                  <a class="text-dark" href="{% url 'criticalpath:ebook_detail' ebook.id %}">{{ ebook.title }}</a>
                </h3>
              </div>


            </div>
            <!-- End Card Body -->

            <!-- Card Footer -->
            <div class="card-footer pt-0">
              <div class="d-flex justify-content-between align-items-center">
                <div class="me-2">
                  <h5 class="card-title">{% if ebook.currency_type.iso_code == "USD"  %} ${% endif %}{{ ebook.price }} {% if ebook.currency_type.iso_code == "SAT" %} sats {% else %} {{ebook.currency_type.iso_code}} {% endif %}</h5>
                </div>
                <a class="btn btn-outline-primary btn-sm btn-transition" href="{% url 'criticalpath:ebook_update' ebook.id %}">Edit</a>
                <a class="btn btn-primary btn-sm btn-transition" href="{% url 'criticalpath:ebook_detail' ebook.id %}">View</a>
              </div>
            </div>
            <!-- End Card Footer -->
          </div>
          <!-- End Card -->
        </div>
        <!-- End Col -->
        {% endfor %}
      </div>
      <!-- End Row -->



    </div>
    <!-- End Card Grid -->
    {% else %}
    <div class="container content-space-1 content-space-sm-1">
      <div class="row mt-9">
        <div class="col-12 mb-5">
          <h1>✨ Creator</h1>
          <p>Thank you for your interest in emeralize Creator! Please complete the review of our Terms and Privacy Policy. Once reviewed, if you agree please complete the form.</p>

          <form action="{% url 'criticalpath:creator_signup' %}"  method="post">
            {% csrf_token %}
            <!-- Checkbox -->
            <div class="form-check mb-3">
              <input type="checkbox" id="formCheck11" class="form-check-input" name="agree" id="agree" required />
              <label class="form-check-label" for="formCheck11">I agree to the <a href="{% url 'marketplace:terms' %}">Terms of Use</a> and the <a href="{% url 'marketplace:privacy' %}">Privacy Policy</a></label>
            </div>
            <!-- End Checkbox -->
            <button class="btn btn-primary" type="submit">Continue</button>

          </form>
      </div>
    </div>
    {% endif %}

{% endblock %}

app/criticalpath/templates/criticalpath/ebook_confirm_delete.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
Delete {{ebook.title}}
{% endblock %}
{% block content %}
<div class="container content-space-2 content-space-lg-3">
    <div class="row">
        <div class="col-12">
          <h1>Delete 
          {% if ebook %} {{ebook.title}} {% endif %}
          {% if course %} {{course.title}} {% endif %}
        </h1>
        
        <p>Are you sure you want to delete the 
          {% if ebook %} Ebook : {{ ebook.title }}?{% endif %}
          {% if course %} Course : {{ course.title }}?{% endif %}
        </p>
        
        <form action="" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit" >Yes Delete.</button>
          
          <input class="btn btn-primary" type="submit" value="Cancel" onclick="window.location.href='{% url 'criticalpath:my-creations' %}';return false;">
        </form>

        </div>
    </div>
</div>

{% endblock %}

app/criticalpath/templates/criticalpath/resource_detail.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
{{ resource.title }} 
{% endblock %}
{% block customhead %}
<style>

  .ql-video {
    width: 100%;
    height: 30em;
  }

</style>
{% endblock %}

{% block content %}
<!-- Content -->
<div class="container content-space-1 content-space-sm-1">

    <div class="row my-6">
        <div class="col-9 ">
            <h2>{{resource.title}}</h2>
            <p>{{resource.excerpt}}</p>
            <div class="d-flex align-items-center flex-wrap">
                <!-- Media -->
                <div class="d-flex align-items-center me-4">
                  <div class="flex-shrink-0 avatar-group avatar-group-xs">
                    <a class="link" href="{% url 'marketplace:user-profile' resource.creator.username %}">
                    <span class="avatar avatar-xs avatar-circle">
                      <img class="avatar-img" src="{{resource.creator.user_profile.profile_pic.url}}" alt="Image Description">
                    </span>
                  </div>
                  <div class="flex-grow-1">
                    <span class="ps-2">{{resource.creator.username}}</span></a>
                    {% if course %} {{resource_sequence.order_no}} out of {{max_sequence_number.order_no__max}} {% endif %}
                  </div>

                </div>
                <!-- End Media -->
            </div>
            <!-- End Col -->
            </div>
            <div class="col-3 my-3">
                {% if request.user == resource.creator %}
                <a class="btn btn-primary" href="{% url 'criticalpath:resource_update' resource.id %}">Edit</a>
                <a class="btn btn-outline-primary" href="{% url 'criticalpath:resource_delete' resource.id %}">Delete</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'marketplace:tip-amount' resource.creator.username %}">Tip</a>
                {% endif %}
            </div>
          </div>
          <!-- End Row -->
        <div class="row">
            <div class="col-12">
                <div class="border-top"></div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col">
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-success my-2" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <div class="mx-auto mt-5 mb-5 d-inline">
                    <div class="p-4 border" style="border-radius: .3em; border-color: #049070 !important;">
                      {% if resource.video %}
                      <video class="ratio ratio-16x9" controls>
                        <source src="{{resource.video.url}}" type="video/mp4">
                        Your browser does not support the video tag.
                      </video>
                      {% endif %}
                        {{ resource.content.html|safe }}
                    </div>
                </div>
                {% if resource.file %}  
                <a class="btn btn-primary my-3" href="{{resource.file.url}} " target="_blank">Download</a>
                {% endif %}
                {% comment %} {% if resource.price > 0 and resource.creator != request.user %} {% endcomment %}

                {% comment %} {% if user.is_authenticated and resource.creator != request.user %}
                    {% if rewardRedeemed %}
                        <p>Congratulations! You earned 10 sat on completing this resource.</p>

                    {% else %}
 
                        <a class="btn btn-primary" href="{% url 'criticalpath:resource_reward_user' course.id resource.id %}">Complete</a>

                {% endif %} 
                {% endif %}{% endcomment %}
                {% if course %}
                  {% if prev_back_to_course %}
                    <a class="btn btn-outline-primary my-3" href="{% url 'criticalpath:course_detail' course.id  %}">Back</a>
                  {% else %}
                    <a class="btn btn-outline-primary my-3" href="{% url 'criticalpath:course_resource_detail' course.id prev_resource.id %}">Back</a>
                  {% endif %}
                  {% if next_back_to_course %}
                    <a class="btn btn-primary my-3" href="{% url 'criticalpath:course_detail' course.id  %}">Next</a>
                  {% else %}
                    <a class="btn btn-primary my-3" href="{% url 'criticalpath:course_resource_detail' course.id next_resource.id %}">Next</a>
                  {% endif %}
                {% endif %}
            </div>

    </div>
  </div>

<!-- End Content -->

{% endblock %}