app/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# from .forms import CaptchaPasswordResetForm


urlpatterns = [
    path('logout_user/', views.logout_view, name="logout_user"),
    path('register_user/', views.register_user, name="register"),
    path('help/', views.help, name="help"),
    path('password/', views.change_password, name='change_password'),
    path('logout_user/', views.logout_view, name="logout_user"),
    path('signin/', views.login_user, name="signin"),
    path("password_reset/", auth_views.PasswordResetView.as_view()),

    # path("password_reset/", auth_views.PasswordResetView.as_view(form_class=CaptchaPasswordResetForm)),

] 

app/criticalpath/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings


from . import views

app_name='criticalpath'
urlpatterns = [
    path('journeys/', views.journey_list, name='journey_list'),
    path('my-criticalpath/', views.UserCriticalPathDetailView.as_view(), name='my-criticalpath'),
    # path('my-saved-journeys', views.UserSavedJourneysListView.as_view(), name='my-saved-journeys'),
    # path('journey/<int:pk>/', views.JourneyDetailView.as_view(), name='journey_detail'),
    # path('journey/create/',
    #     views.JourneyCreateView.as_view(success_url=reverse_lazy('criticalpath:phase_create')), name='journey_create'),
    # path('journey/<int:pk>/update/',
    #     views.JourneyUpdateView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_update'),
    # path('journey/<int:pk>/delete/',
    #     views.JourneyDeleteView.as_view(success_url=reverse_lazy('criticalpath:journey_list')), name='journey_delete'),
    # path('journey/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
    # path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy('journey_list')), name='comment_delete'),
    # path('journey/<int:pk>/favorite',
    #     views.AddFavoriteView.as_view(), name='journey_favorite'),
    # path('journey/<int:pk>/unfavorite',
    #     views.DeleteFavoriteView.as_view(), name='journey_unfavorite'),
    # path('journey/<int:journey_pk>/resource/', views.ResourceAddView.as_view(success_url=reverse_lazy('criticalpath:journey_detail')), name='resource_add'),

    path('resource/create/', views.ResourceCreateView.as_view(success_url=reverse_lazy('home')), name='resource_create'),
    path('resource/<int:resource_pk>/', views.ResourceDetailView.as_view(), name='resource_detail'),
    path('resource/<int:resource_pk>/update/', views.ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/<int:resource_pk>/delete/', views.ResourceDeleteView.as_view(), name='resource_delete'),

    path('ebook/create/', views.EbookCreateView.as_view(success_url=reverse_lazy('home')), name='ebook_create'),
    path('ebook/<int:ebook_pk>/splits/', views.EbookPaymentSplitsView.as_view(), name='ebook_add_splits'),
    path('ebook/<int:ebook_pk>/', views.EbookDetailView.as_view(), name='ebook_detail'),
    path('ebook/<int:ebook_pk>/update/', views.EbookUpdateView.as_view(), name='ebook_update'),
    path('ebook/<int:ebook_pk>/delete/', views.EbookDeleteView.as_view(), name='ebook_delete'),

    path('workshop/create/', views.WorkshopCreateView.as_view(success_url=reverse_lazy('home')), name='workshop_create'),
    path('workshop/<int:workshop_pk>/splits/', views.WorkshopPaymentSplitsView.as_view(), name='workshop_add_splits'),
    path('workshop/<int:workshop_pk>/', views.WorkshopDetailView.as_view(), name='workshop_detail'),
    path('workshop/<int:workshop_pk>/update/', views.WorkshopUpdateView.as_view(), name='workshop_update'),
    path('workshop/<int:workshop_pk>/delete/', views.WorkshopDeleteView.as_view(), name='workshop_delete'),

    path('course/create/', views.CourseCreateView.as_view(success_url=reverse_lazy('criticalpath:creator')), name='course_create'),
    path('course/<int:course_pk>/add/', views.CourseAddResourcesView.as_view(), name='course_add_resources'),
    path('course/<int:course_pk>/splits/', views.CoursePaymentSplitsView.as_view(), name='course_add_splits'),
    path('course/<int:course_pk>/resource/<int:resource_pk>/', views.CourseResourceDetailView.as_view(), name='course_resource_detail'),
    path('course/<int:course_pk>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('course/<int:course_pk>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course/<int:course_pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),



    path('creator/', views.creation_list, name="my-creations"),
    path('creator/signup/', views.creator_signup, name="creator_signup"),

    # uncomment if you want to enable rewards
    # path('course/<int:course_pk>/resource/<int:resource_pk>/reward/', views.reward_user, name="resource_reward_user"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/emeralize/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy, include
from marketplace.views import homepage
from marketplace import views
from accounts.views import confirm
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static
from django_email_verification import urls as email_urls  # include the urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="home"),
    path('', include('marketplace.urls')),
    path('', include('criticalpath.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(email_urls)),  # connect them to an arbitrary path
    # path('email/<str:token>/', confirm), # remember to set the "token" parameter in the url!


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "marketplace.views.handle_not_found"

# if settings.DEBUG:
#     urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL,  
                        document_root=settings.MEDIA_ROOT) 

app/marketplace/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth.views import LoginView,LogoutView
from marketplace import views
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls.static import static


app_name='marketplace'
urlpatterns = [
    path('marketplace/', discover, name='discover'),
    path('marketplace/resources/', resource_list, name='resource_list'),
    path('journey/<int:pk>/buy/', journey_buy_view, name="journey_buy"),

    path('resource/<int:pk>/buy/', resource_buy_view, name="resource_buy"),
    path('resource/purchase_detail/<int:pk>/', views.ResourcePurchaseDetailView.as_view(), name="resource_purchase_detail"),
    path('resource/<int:resource>/buy/success/', resource_success, name="resource_success"),

    path('ebook/<int:pk>/buy/', ebook_buy_view, name="ebook_buy"),
    path('ebook/purchase_detail/<int:pk>/', views.EbookPurchaseDetailView.as_view(), name="ebook_purchase_detail"),
    path('ebook/<int:ebook>/buy/success/', ebook_success, name="ebook_success"),

    path('workshop/<int:pk>/buy/', workshop_buy_view, name="workshop_buy"),
    path('workshop/purchase_detail/<int:pk>/', views.WorkshopPurchaseDetailView.as_view(), name="workshop_purchase_detail"),
    path('workshop/<int:workshop>/buy/success/', workshop_success, name="workshop_success"),

    path('course/purchase_detail/<int:pk>/', views.CoursePurchaseDetailView.as_view(), name="course_purchase_detail"),
    path('course/<int:pk>/buy/', course_buy_view, name="course_buy"),
    path('course/<int:course>/buy/success/', course_success, name="course_success"),

    path('journey/<int:journey>/buy/success/', journey_success, name="journey_success"),
    path('webhook/zbd/', csrf_exempt(zbd_webhook), name="charge_callback"),
    path('charge-status/', charge_status_check),
    path('purchase-history/', purchase_history, name="purchase-history"),
    path('transaction-history/', transaction_history, name="transaction-history"),
    path('accounts/profile/', views.UserProfileCreate.as_view(), name="account-profile"),
    path('profile/<username>/', profile, name="user-profile"),
    path('profile/<username>/tip/', tip_amount, name="tip-amount"),
    path('profile/<username>/tip/pay/', tip_pay, name="tip-pay"),
    path('profile/<username>/tip/pay/success/', tip_success, name="tip-success"),
    path('wallet/', wallet_view, name="wallet"),
    path('withdrawal/', withdrawal, name="withdrawal"),
    path('terms/', terms, name="terms"),
    path('privacy/', privacy, name="privacy"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/criticalpath/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from django.core import validators
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from criticalpath.humanize import naturalsize
from django.forms import ModelForm, Select
from captcha.fields import ReCaptchaField


from marketplace.models import UserProfile
from django.core import validators

class CreatorSignUpForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['creator']

class JourneyForm(ModelForm):
    class Meta:
        model = Journey
        fields = ['title', 'objective', 'category', 'price', 'cover_image']


class CourseForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Course
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price' ]

class CourseAddResourcesForm(ModelForm):
    class Meta:
        model = CourseResources
        fields = ['resource', 'order_no' ]

class CoursePaymentSplitsForm(ModelForm):
    class Meta:
        model = CoursePaymentSplits
        fields = ['user', 'amount' ]

# class PhaseForm(ModelForm):
#     class Meta:
#         model = Phase
#         fields = ['title', 'description']

class EbookForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Ebook
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'currency_type', 'file', 'content' ]

class EbookPaymentSplitsForm(ModelForm):
    class Meta:
        model = EbookPaymentSplits
        fields = ['user', 'amount' ]

class WorkshopForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Workshop
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'currency_type', 'content' ]

class WorkshopPaymentSplitsForm(ModelForm):
    class Meta:
        model = WorkshopPaymentSplits
        fields = ['user', 'amount' ]


class ResourceForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Resource
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'content' ]


class SuperResourceForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Resource
        fields = ['status', 'title', 'excerpt', 'cover_image', 'price', 'content', 'file', 'video']


class AddResourceForm(ModelForm):
    class Meta:
        model = JourneyResources
        fields = ['resource']


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)


# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

app/criticalpath/templates/criticalpath/workshop/workshop_confirm_delete.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
Delete {{workshop.title}}
{% endblock %}
{% block content %}
<div class="container content-space-2 content-space-lg-3">
    <div class="row">
        <div class="col-12">
          <h1>Delete 
          {% if workshop %} {{workshop.title}} {% endif %}
        </h1>
        
        <p>Are you sure you want to delete the 
          {% if workshop %} workshop : {{ workshop.title }}?{% endif %}
        </p>
        
        <form action="" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit" >Yes Delete.</button>
          
          <input class="btn btn-primary" type="submit" value="Cancel" onclick="window.location.href='{% url 'criticalpath:my-creations' %}';return false;">
        </form>

        </div>
    </div>
</div>

{% endblock %}

app/criticalpath/templates/criticalpath/workshop/workshop_detail.html
{% extends "emeralize/base.html" %}
{% load static %}
{% block title %}
{{ workshop.title }} 
{% endblock %}
{% block customhead %}
<style>

  .ql-video {
    width: 100%;
    height: 30em;
  }

</style>
{% endblock %}

{% block content %}
<!-- Content -->
<div class="container content-space-1 content-space-sm-1">

    <div class="row my-6">
        <div class="col-9 ">
            <h2>{{workshop.title}}</h2>
            <p>{{workshop.excerpt}}</p>
            <div class="d-flex align-items-center flex-wrap">
                <!-- Media -->
                <div class="d-flex align-items-center me-4">
                  <div class="flex-shrink-0 avatar-group avatar-group-xs">
                    <a class="link" href="{% url 'marketplace:user-profile' workshop.creator.username %}">
                    <span class="avatar avatar-xs avatar-circle">
                      <img class="avatar-img" src="{{workshop.creator.user_profile.profile_pic.url}}" alt="Image Description">
                    </span>
                  </div>
                  <div class="flex-grow-1">
                    <span class="ps-2">{{workshop.creator.username}}</span></a>
                  </div>

                </div>
                <!-- End Media -->
            </div>
            <!-- End Col -->
            </div>
            <div class="col-3 my-3">
                {% if request.user == workshop.creator %}
                <a class="btn btn-primary" href="{% url 'criticalpath:workshop_update' workshop.id %}">Edit</a>
                <a class="btn btn-outline-primary" href="{% url 'criticalpath:workshop_delete' workshop.id %}">Delete</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'marketplace:tip-amount' workshop.creator.username %}">Tip</a>
                {% endif %}
            </div>
          </div>
          <!-- End Row -->
        <div class="row">
            <div class="col-12">
                <div class="border-top"></div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col">
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-success my-2" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                <div class="mx-auto mt-5 mb-5 d-inline">
                    <div class="p-4 border" style="border-radius: .3em; border-color: #049070 !important;">
                      {% if workshop.video %}
                      <video class="ratio ratio-16x9" controls>
                        <source src="{{workshop.video.url}}" type="video/mp4">
                        Your browser does not support the video tag.
                      </video>
                      {% endif %}
                        {{ workshop.content.html|safe }}
                    </div>
                </div>


            </div>

    </div>
  </div>

<!-- End Content -->

{% endblock %}

app/criticalpath/templates/criticalpath/workshop/workshop_form.html
{% extends "emeralize/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{header_name}}
{% endblock %}
{% block customhead %}
<style>
  .ql-toolbar .ql-stroke {
      fill: none;
      stroke: #ABB5BE !important;
  }

  .ql-toolbar .ql-fill {
      fill: #ABB5BE !important;
      stroke: none;
  }

  .ql-toolbar .ql-picker {
      color: #ABB5BE !important;
  }
  .ql-container.ql-snow {
    border: 0.0625rem solid #AAA8AE;
  }
  .ql-toolbar.ql-snow + .ql-container.ql-snow {
    border-top: 0px;
    background: #11142C;
  }
  .ql-toolbar.ql-snow {
    border: 0.0625rem solid #AAA8AE !important;
    box-sizing: border-box;
    font-family: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
    padding: 8px;
    background: #11142C;
    color: #ABB5BE !important;
  }
  
  
</style>
{{ form.media }}
{% endblock %}

{% block content %}
        
      <div class="container content-space-2 content-space-lg-3">
      <!-- Page Header -->
      <div class="page-header">
        <div class="row align-items-center">
          <div class="col-sm mb-2">

            <a class="btn btn-primary btn-sm mb-4" href="{% url 'criticalpath:my-creations' %}">
              <i class="bi-arrow-left me-1"></i> Back
            </a>
            <h2 class="page-header-title">{{header_name}}</h2>
          </div>

          <div class="col-sm-auto">
            {% if workshop %}
            <a class="btn btn-outline-primary" href="{% url 'criticalpath:workshop_delete' workshop.id %}">Delete</a>
            {% endif %}

          </div>
        </div>
      </div>
      <!-- End Page Header -->
      {% if form.errors %}
      <div class="alert alert-danger" role="alert">

      There was an error with your form.

      </div>
      {% endif %}
      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">{{ message }}</div>
          {% endfor %}
      {% endif %}
      <div class="row align-items-center">
        <div class="col-sm-12 col-md-8">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <table>
            {{ form|crispy }}
          </table>
          <a class="btn btn-outline-primary" href="{% url 'criticalpath:my-creations' %}">
            <i class="bi-arrow-left "></i> Back
          </a>
          <input class="btn btn-primary" type="submit" value="Next">
        </form>
        </div>
      </div>
    </div>
{% endblock %}

app/criticalpath/templates/criticalpath/workshop/workshop_payment_splits.html
{% extends "emeralize/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{header_name}}
{% endblock %}

{% block content %}
        
      <div class="container content-space-2 content-space-lg-3">
      <!-- Page Header -->
      <div class="page-header">
        <div class="row align-items-center">
          <div class="col-sm mb-2">
            <h2 class="page-header-title">Payment Splitting</h2>
            <p>Payment splitting using Bitcoin is a secure and easy process that can be done by providing the creators and specifying the percentage to split amongst each party.</p>
          </div>

          <div class="col-sm-auto">
            {% if workshop %}
            <a class="btn btn-outline-primary" href="{% url 'criticalpath:workshop_delete' workshop.id %}">Delete</a>

            {% endif %}
          </div>
        </div>
      </div>
      <!-- End Page Header -->
      <form action="{% url 'criticalpath:workshop_add_splits' workshop.id %}" method="post">
        {% csrf_token %}
        <div class="row align-items-center" id="row-owner">
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% endfor %}
          {% endif %}
          <div class="col-sm-6">
            <!-- Form -->
            <div class="mb-4">
              <label class="form-label" >Your Share</label>
              <select id="owner-user" name="owner-user" class="form-select form-select-lg" readonly="readonly">
                <option value="{{request.user.id}}" selected>{{request.user.username}}</option>
              </select>
            </div>
            <!-- End Form -->

          </div>

          <div class="col-sm-3">
            <!-- Form -->
            <div class="mb-4">
              <label class="form-label" >Share %</label>
              <input type="number" value="{{creator_share}}" min="1" step="1" id="split-owner-amount" name="owner-amount" class="form-select form-select-lg" readonly="readonly">
            </div>
            <!-- End Form -->
  
          </div>
        {% if payment_splits %}

          {% for payment_split in payment_splits %}
          <div class="row align-items-center" id="row-{{payment_split.id}}">
            <div class="col-sm-6">
              <!-- Form -->
              <div class="mb-4">
                <label class="form-label" >Creator</label>
                <select id="{{payment_split.user.username}}" name="{{payment_split.user.username}}" class="form-select form-select-lg" >
                  <option value="{{payment_split.user.id}}" selected>{{payment_split.user.username}}</option>
                  {% if creators %}
                  {% for creator in creator %}
                  <option value="{{creator.user.id}}">{{creator.user.username}}</option>
                  {%endfor%}
  
                {% endif %}
                </select>
              </div>
              <!-- End Form -->

            </div>


            <div class="col-sm-3">
              <!-- Form -->
              <div class="mb-4">
                <label class="form-label" >Share %</label>
                <input type="number" value="{{payment_split.amount}}" min="1" step="1" id="{{payment_split.user.username}}-amount" name="{{payment_split.user.username}}-amount" class="form-select form-select-lg" >
              </div>
              <!-- End Form -->

            </div>

            <div class="col-sm-3">
              <!-- Form -->
              <div class="mb-4">
                <div>
                  <label class="form-label" for="hireUsFormLasttName">Action</label>
                </div>
                <button type="button" onclick="removeInputs()" class="btn btn-outline-primary" id="del-{{payment_split.id}}"><i class="bi bi-trash"></i></button>

              </div>
              <!-- End Form -->
            
            </div>

          <!-- End Form -->
          </div>

          {%endfor%}


 
        </div>

          {% endif %}
          <div id="add_split_list">

          </div>
          <div class ="row align-items-center">
            <div class="col-12 mb-3">
              <button type="button" onclick="addInputs()" class="btn btn-primary" id="add1"><i class="bi bi-plus"></i></button>
            </div>
            <div class="col-12">
              <a class="btn btn-outline-primary" href="{% url 'criticalpath:workshop_update' workshop.id %}">
                <i class="bi-arrow-left "></i> Back
              </a>
              <button type="submit" class="btn btn-primary">Next</button>
            </div>
          </div>
        </div>
  
        </form>
        </div>
    </div>
{% endblock %}

{% block customjs %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
  start_add_row = {{payment_splits|length}};


  function addInputs () {
    start_add_row += 1
    $('#add_split_list').append(`
      <div class="row" id="row-${start_add_row}">
        <div class="col-sm-6">

        <!-- Form -->
        <div class="mb-4">
          <label class="form-label">Creator</label>
          <select name="creator-${start_add_row}" id="creator-${start_add_row}" class="form-select form-select-lg" >
            <option selected>Please select another creator.</option>
            {% for creator in creators %}
            <option value="{{creator.user.id}}">{{creator.user.username}}</option>
            {%endfor%}
          </select>
        </div>
        <!-- End Form -->

        </div>

        <div class="col-sm-3">
          <!-- Form -->
          <div class="mb-4">
            <label class="form-label" >Share %</label>
            <input type="number" min="1" step="1" id="amount-${start_add_row}" name="amount-${start_add_row}" class="form-select form-select-lg" >
          </div>
          <!-- End Form -->

        </div>

        <div class="col-sm-3">
          <!-- Form -->
          <div class="mb-4">
            <div>
              <label class="form-label" for="hireUsFormLasttName">Action</label>
            </div>
            <button type="button" class="btn btn-outline-primary" id="del-${start_add_row}"><i class="bi bi-trash"></i></button>

          </div>
          <!-- End Form -->
        
        </div>
        </div>
    `);

    row = "row-" + start_add_row;
    del = "del-" + start_add_row;
    document.getElementById(del).addEventListener("click", removeInputs);
    };

  function removeInputs (e) {
    let element = e.target.id;
    element_split = element.split("-");
    let num = element_split[1];
    $("div").remove("#row-"+num);
  }

  {%comment%} add event listeners for all existing rows for deletion / update {%endcomment%}
  {% comment %} let number_of_resources = 1; {% endcomment %}
  {% for split in payment_splits %}
    existing_dels = "del-" + {{split.id}};
    document.getElementById(existing_dels).addEventListener("click", removeInputs);
  {% endfor %}

</script>

{% endblock %}